apiVersion: apps/v1
kind: Deployment
metadata:
  name: helixai-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helixai-api
  template:
    metadata:
      labels:
        app: helixai-api
    spec:
      serviceAccountName: helixai-api
      containers:
        - name: helixai-api
          image: helixai-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: helixai-secret
                  key: DATABASE_URL
            - name: HELIXAI_ENVIRONMENT
              value: kubernetes
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROMETHEUS_URL
              value: http://prometheus:9090
            - name: GRAFANA_URL
              value: http://grafana:3000
            - name: VAULT_URL
              value: http://vault:8200
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: JENKINS_JOB
              value: helixai
